### ISSUE TITLE
Feature request: Add support for macOS / AArch64 

### ISSUE THREAD

**Issue by gunnarmorling** [datafusion-contrib/datafusion-java#137]
Hi, are there plans for adding support for macOS / AArch64 (i.e. M1 Macs) to this library? I am getting this error below which I suppose is the case as the native library only is built for macOS/x64:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/2h/dglkh0gd07jfc6bqgx5g94nm0000gn/T/datafusion_jni4772271915185568606.dylib
```

**Comment by caicancai** [comment]
> Hi, are there plans for adding support for macOS / AArch64 (i.e. M1 Macs) to this library? I am getting this error below which I suppose is the case as the native library only is built for macOS/x64:
> 
> ```
> Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/2h/dglkh0gd07jfc6bqgx5g94nm0000gn/T/datafusion_jni4772271915185568606.dylib
> ```

I have no problem with the M3 Mac
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/c3f7a1d6-8cca-4d74-85e7-e873e76aa299">

**Comment by jimexist** [comment]
> > Hi, are there plans for adding support for macOS / AArch64 (i.e. M1 Macs) to this library? I am getting this error below which I suppose is the case as the native library only is built for macOS/x64:
> > ```
> > Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/2h/dglkh0gd07jfc6bqgx5g94nm0000gn/T/datafusion_jni4772271915185568606.dylib
> > ```
> 
> I have no problem with the M3 Mac <img alt="image" width="1437" src="https://private-user-images.githubusercontent.com/77189278/382327384-c3f7a1d6-8cca-4d74-85e7-e873e76aa299.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NzY0MzksIm5iZiI6MTczMDQ3NjEzOSwicGF0aCI6Ii83NzE4OTI3OC8zODIzMjczODQtYzNmN2ExZDYtOGNjYS00ZDc0LTg1ZTctZTg3M2U3NmFhMjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDE1NDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMGNmNDFjZDEzZjBkOGE5YWU4MGVmNzIxNzJlMDg1ZGQxNWYyOGQ2MDVmZGU1OWQ4NWQzMmEzM2NmZGNhMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IKgxGfg1kQTs03n6o3Pr8l9ZI5-wJjAOKoUaSiqGI-I">

i think the issue was not about local dev. it's about the packaged version.

we use GitHub runner to package and as of the time of last publish the runner had no M1 version.

GitHub seemed to have added M series support but not sure if's available for free for open source - see https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories maybe worth trying it out

**Comment by bvolpato** [comment]
Right, having the same issue with M4:

```
Unsupported OS/arch (`Osx' detected), cannot find `/jni_libs/libdatafusion_jni.dylib' or load `datafusion_jni' from system libraries. Please try building from source the jar or providing datafusion_jni in your system.
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2458)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
        at java.base/java.lang.System.loadLibrary(System.java:2063)
        at org.apache.arrow.datafusion.JNILoader.load(JNILoader.java:95)
        at org.apache.arrow.datafusion.SessionContexts.<clinit>(SessionContexts.java:33)
```
